name: 提取配置信息

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 检出代码
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.PAT }}

      - name: 初始化Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"

      - name: 提取配置信息
        env:
          INSPECT_WECHAT_HOOK_KEY: ${{ secrets.INSPECT_WECHAT_HOOK_KEY }}
          INSPECT_TELEGRAM_BOT_TOKEN: ${{ secrets.INSPECT_TELEGRAM_BOT_TOKEN }}
          INSPECT_TELEGRAM_CHAT_ID: ${{ secrets.INSPECT_TELEGRAM_CHAT_ID }}
          INSPECT_AES_KEY: ${{ secrets.INSPECT_AES_KEY }}
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install requests==2.33.1 pycryptodome==3.23.0
          python3 inspect_configs.py

      - name: 清理敏感日志
        if: always()
        run: echo "::add-mask::${{ secrets.CONFIG }}"
