name: 刷步数

on:
  schedule:
    - cron: '7 0,2,4,6,8,14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 检出代码
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.PAT }}

      - name: 初始化Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip3 install requests==2.33.1 pytz==2026.1.post1 pycryptodome==3.23.0

      - name: 执行刷步数
        env:
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}
        run: python3 main.py

      - name: 保存令牌文件
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add encrypted_tokens.data
          git diff --cached --quiet || git commit -m "persist tokens trigger by ${{ github.event_name }}"
          git pull --rebase origin master
          git push origin master
